# environment
domain_name: cheetah
task_name: run
# crop 
pre_transform_image_size: 100
image_size: 84
# action and obs
action_repeat: 4
frame_stack: 3
# train
agent: curl_sac
init_steps: 1000
num_train_steps: 1000000
replay_buffer_capacity: 100000
batch_size: 128
hidden_dim: 1024
#eval
eval_freq: 1000
num_eval_episodes: 10
# critic
critic_lr: 0.001 
critic_beta: 0.9
critic_tau: 0.01
critic_target_update_freq: 2
# actor
actor_lr: 0.001
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2
# encoder
encoder_type: pixel
encoder_feature_dim: 50
encoder_lr: 0.001
encoder_tau: 0.05
num_layers: 4
num_filters: 32
detach_encoder: False 
# curl
curl_latent_dim: 128
# SAC
discount: .99
init_temperature: .1
alpha_lr: 0.0001
alpha_beta: .5
seed: -1
# save & log
work_dir: '/tmp'
save_tb: True 
save_buffer: False 
save_video: False 
save_model: False
log_interval: 100
